version: '3.4'
services:
  db: # Nome do container de MySQL
    image: mysql:5.7.22 # FROM mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    ports:
      - 3308:3306
    networks:
      - wordpress-network
  wordpress:
    image: wordpress:latest # Carregando a imagem do wordpress na sua ultima vers√£o
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    # Acessando o banco
    environment: # Configurando o wordpress para conectar com o DB (seguir o user, senha do mesmo de cima)
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    ports:
      - 8000:80
    networks:
      - wordpress-network
networks:
    wordpress-network:
      driver: bridge

# sudo gpasswd -a $USER docker
# newgrp docker
